import { TemplateEngine } from "../template/template.engine.js";
import { TemplateContext } from "../template/template.types.js";
import { mapToSupportedFramework, mapToSupportedLanguage, mapToPackageManager, slugifyProjectName } from "../template/template.utils.js";
import { GeminiService } from "../clients/gemini.service.js";
import type { GeneratedProject } from "../types/generated-project.types.js";
import type { ProjectPlan } from "../types/project-plan.types.js";
import type { ArchitecturePlan } from "../types/architecture-plan.types.js";
import type { ComponentContract } from "../context/context-builder.types.js";
import { env } from "../../../config/env.js";
import { buildFilePrompt, buildAppPrompt } from "../prompts/generator-v2.prompt.js";
import { installDependenciesInWorkspace } from "../../runtime/install.service.js";
import { getWorkspacePath } from "../../runtime/workspace.service.js";
import { updateWorkspaceFile } from "../../runtime/workspace-file.service.js";

interface V2Metrics {
  totalFiles: number;
  totalApiTime: number;
  fastestFile: number;
  slowestFile: number;
  slowestFileName: string;
  fastestFileName: string;
  totalApiCalls: number;
}

export class GeneratorV2Service {
  private readonly gemini: GeminiService;
  private readonly templateEngine: TemplateEngine;

  constructor(gemini: GeminiService, templateEngine: TemplateEngine) {
    this.gemini = gemini;
    this.templateEngine = templateEngine;
  }

  private cleanRawOutput(output: string): string {
    let content = output.trim();
    // Strip markdown code fences
    const fenceMatch = content.match(/^```\w*\n([\s\S]*)\n```$/);
    if (fenceMatch) {
      content = fenceMatch[1];
    } else {
      // In case the model forgot the closing fence but had an opening one
      if (content.startsWith("```")) {
        const lines = content.split("\n");
        lines.shift();
        if (lines[lines.length - 1].startsWith("```")) lines.pop();
        content = lines.join("\n");
      }
    }
    return content.trim();
  }

  private determineResponsibility(path: string): "root" | "page" | "component" | "store" | "utility" | "config" {
    const lower = path.toLowerCase();
    if (lower.includes("app.tsx") || lower.includes("main.tsx") || lower.includes("index.html")) return "root";
    if (lower.includes("/pages/") || lower.includes("/views/") || lower.includes("/routes/")) return "page";
    if (lower.includes("/components/") || lower.includes("/layouts/")) return "component";
    if (lower.includes("/store/") || lower.includes("/stores/") || lower.includes("/context/") || lower.includes("/state/")) return "store";
    if (lower.includes("/utils/") || lower.includes("/hooks/") || lower.includes("/types/") || lower.includes("/lib/")) return "utility";
    if (lower.endsWith(".config.js") || lower.endsWith(".config.ts") || lower.endsWith(".json")) return "config";
    return "utility"; // fallback
  }

  /**
   * Orchestrates the incremental generation of the project.
   */
  async generateProject(
    projectId: string,
    projectPlan: ProjectPlan,
    architecturePlan: ArchitecturePlan
  ): Promise<GeneratedProject> {
    const startGeneration = performance.now();
    const metrics: V2Metrics = {
      totalFiles: 0,
      totalApiTime: 0,
      fastestFile: Infinity,
      slowestFile: 0,
      slowestFileName: "",
      fastestFileName: "",
      totalApiCalls: 0,
    };

    // Phase 0: Template Engine (Deterministic Boilerplate)
    const deps = architecturePlan.dependencies || [];
    const dependencies = deps.filter(d => !d.isDev).reduce((acc, d) => ({ ...acc, [d.name]: d.version || 'latest' }), {});
    const devDependencies = deps.filter(d => d.isDev).reduce((acc, d) => ({ ...acc, [d.name]: d.version || 'latest' }), {});

    const context: TemplateContext = {
      projectName: slugifyProjectName(projectPlan.applicationType),
      framework: mapToSupportedFramework(architecturePlan.stack.frontendFramework),
      language: mapToSupportedLanguage(architecturePlan.stack.language),
      packageManager: mapToPackageManager(architecturePlan.stack.packageManager),
      features: projectPlan.features,
      dependencies,
      devDependencies
    };

    const templateFiles = this.templateEngine.generateAll(context);
    const templatePaths = new Set(templateFiles.map(f => f.path));

    // Parallel Install
    const workspacePath = getWorkspacePath(projectId);
    const packageJsonFile = templateFiles.find(f => f.path === "package.json");
    let installPromise: Promise<any> | null = null;

    if (packageJsonFile) {
      await updateWorkspaceFile(projectId, packageJsonFile.path, packageJsonFile.content);
      installPromise = installDependenciesInWorkspace(workspacePath, `${context.packageManager} install`);
    }

    // Filter out files that are already generated by templates, EXCEPT index.html which we allow the AI to overwrite
    const aiFiles = architecturePlan.fileStructure.filter(f => {
      if (f.path === "index.html") return true;
      return !templatePaths.has(f.path);
    });

    console.log(`\n--------------------------------`);
    console.log(`Generator V2`);
    console.log(`--------------------------------`);
    console.log(`[GeneratorV2] Template-Owned Files: ${templateFiles.length} | AI Files: ${aiFiles.length}`);

    // Build contracts lookup map
    const allContracts: Record<string, Omit<ComponentContract, "description">> = {};
    if (architecturePlan.componentContracts) {
      for (const contract of architecturePlan.componentContracts) {
        allContracts[contract.name] = contract;
      }
    }

    // Organize AI files into layers
    const layers = [
      { name: "shared", responsibilities: ["utility", "store", "config"] },
      { name: "components", responsibilities: ["component"] },
      { name: "pages", responsibilities: ["page"] },
      { name: "root", responsibilities: ["root"] }
    ];

    const generatedFiles: Array<{ path: string; content: string }> = [];

    // Generator Worker Queue
    const executeQueue = async (files: typeof aiFiles) => {
      let activeCount = 0;
      let hasError = false;
      const queue = [...files];

      // Limit by MAX_PARALLEL_GENERATIONS config, or bounded by healthy models * 2
      const healthyModels = Math.max(1, this.gemini.getHealthyModelCount());
      const maxConcurrency = Math.min(env.MAX_PARALLEL_GENERATIONS, healthyModels * 2);

      await new Promise<void>((resolve, reject) => {
        const next = () => {
          if (hasError) return;
          if (queue.length === 0 && activeCount === 0) return resolve();

          while (activeCount < maxConcurrency && queue.length > 0) {
            const file = queue.shift()!;
            activeCount++;

            this.generateFile(file, projectPlan, architecturePlan, allContracts, metrics)
              .then((result) => {
                generatedFiles.push(result);
                activeCount--;
                next();
              })
              .catch((err) => {
                hasError = true;
                reject(err);
              });
          }
        };
        next();
      });
    };

    for (const layerDef of layers) {
      const layerFiles = aiFiles.filter(f => layerDef.responsibilities.includes(this.determineResponsibility(f.path)));
      if (layerFiles.length === 0) continue;

      console.log(`[GeneratorV2] Starting Layer ${layerDef.name} (${layerFiles.length} files)`);
      await executeQueue(layerFiles);
      console.log(`[GeneratorV2] Layer ${layerDef.name} Finished`);
    }

    // Output Benchmarks
    const totalTimeMs = performance.now() - startGeneration;
    const avgTime = metrics.totalFiles > 0 ? (metrics.totalApiTime / metrics.totalFiles) : 0;

    console.log(`
--------------------------------
Generator V2 Benchmark
--------------------------------
Files Generated: ${metrics.totalFiles}
Average File Time: ${(avgTime / 1000).toFixed(2)}s
Slowest File: ${metrics.slowestFileName} (${(metrics.slowestFile / 1000).toFixed(2)}s)
Fastest File: ${metrics.fastestFileName} (${(metrics.fastestFile / 1000).toFixed(2)}s)
Total API Calls: ${metrics.totalApiCalls}
Generation Time: ${(totalTimeMs / 1000).toFixed(2)}s
--------------------------------
`);

    if (installPromise) {
      console.log(`[GeneratorV2] Awaiting parallel dependency installation...`);
      await installPromise.catch(e => console.error("[GeneratorV2] Install failed in background:", e.message));
      console.log(`[GeneratorV2] Parallel dependency installation completed.`);
    }

    return {
      files: [...templateFiles, ...generatedFiles],
      commands: {
        install: `${context.packageManager} install`,
        build: `${context.packageManager} build`,
        dev: `${context.packageManager} dev`
      },
      project: {
        framework: context.framework,
        language: context.language,
        packageManager: context.packageManager,
        outputDirectory: "dist"
      }
    };
  }

  private async generateFile(
    file: ArchitecturePlan["fileStructure"][0],
    projectPlan: ProjectPlan,
    architecturePlan: ArchitecturePlan,
    allContracts: Record<string, Omit<ComponentContract, "description">>,
    metrics: V2Metrics
  ): Promise<{ path: string; content: string }> {
    const isRoot = this.determineResponsibility(file.path) === "root";

    const behavioralContract = (architecturePlan.behavioralContracts || []).find(
      c => c.file === file.path
    );

    let promptObj: { system: string, prompt: string };
    if (isRoot) {
      promptObj = buildAppPrompt(file, projectPlan, architecturePlan, allContracts, behavioralContract);
    } else {
      promptObj = buildFilePrompt(file, architecturePlan, allContracts, behavioralContract);
    }

    metrics.totalApiCalls++;

    const start = performance.now();
    const rawOutput = await this.gemini.generateText(promptObj.prompt, promptObj.system, {
      timeoutMs: env.GEMINI_GENERATOR_TIMEOUT_MS,
      taskName: `Generate ${file.path}`
    });
    const duration = performance.now() - start;

    metrics.totalFiles++;
    metrics.totalApiTime += duration;

    if (duration > metrics.slowestFile) {
      metrics.slowestFile = duration;
      metrics.slowestFileName = file.path;
    }
    if (duration < metrics.fastestFile) {
      metrics.fastestFile = duration;
      metrics.fastestFileName = file.path;
    }

    console.log(`[GeneratorV2] Generated ${file.path} in ${(duration / 1000).toFixed(2)}s`);

    return {
      path: file.path,
      content: this.cleanRawOutput(rawOutput)
    };
  }
}
