import { z } from "zod";

/**
 * GeneratedProject Schema
 *
 * Represents the final output of the Generator phase (the BUILD).
 * The Generator consumes the ProjectPlan (WHAT) and ArchitecturePlan (HOW)
 * to produce this GeneratedProject contract.
 */
export const generatedProjectSchema = z.object({
  /**
   * Why it exists: This is the actual source code of the application generated by the AI.
   * Consumed by:
   * - Validator: to run TypeScript/ESLint checks against the file contents.
   * - Auto-Fix: to parse, patch, and rewrite broken files based on validation errors.
   * - Preview Engine: to write the files to the virtual file system (e.g., WebContainers).
   */
  files: z.array(
    z.object({
      path: z.string().describe("The relative file path, e.g., 'src/App.tsx'"),
      content: z.string().describe("The complete, raw source code of the file"),
    })
  ),

  /**
   * Why it exists: The AI determines exactly how to bootstrap the project it generated,
   * preventing the backend from making brittle, hardcoded assumptions about the toolchain.
   * Consumed by:
   * - Preview Engine: to install packages, build, and start the live development server.
   * - Validator: to run the build command to check for compilation errors.
   */
  commands: z.object({
    install: z.string().describe("The command to install dependencies, e.g., 'pnpm install'"),
    build: z.string().describe("The command to build the project, e.g., 'pnpm build'"),
    dev: z.string().describe("The command to start the dev server, e.g., 'pnpm dev'"),
  }),

  /**
   * Why it exists: Makes the GeneratedProject completely self-contained for downstream phases.
   * Describes the immutable truth of the project that was actually generated.
   * Consumed by:
   * - Preview Engine: to know which package manager commands to execute natively.
   * - Export Engine: to know whether to generate package-lock.json or pnpm-lock.yaml.
   */
  project: z.object({
    framework: z.string().describe("The frontend framework used (e.g., 'React')"),
    language: z.string().describe("The programming language used (e.g., 'TypeScript')"),
    packageManager: z.string().describe("The package manager required (e.g., 'pnpm', 'npm')"),
    outputDirectory: z.string().describe("The directory where build artifacts are placed (e.g., 'dist', 'build')"),
  }).describe("Immutable facts about the generated project stack"),
});
